version: '3'

services:
  rabbitmq:
    image: 'docker.io/bitnami/rabbitmq:3.8-debian-10'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 30s
      timeout: 15s
      retries: 1
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rabarbar123
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rabarbar123
  sender:
    build: ./Sender
    restart: on-failure
    depends_on:
      - rabbitmq
  receiver:
    build: ./Receiver
    restart: on-failure
    depends_on:
      - rabbitmq
  website:
    build: ./Website
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 3000:3000
volumes:
  rabbitmq_data:
    driver: local
